spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    remote:
      secret: 123
    restart:
      enabled: false
      trigger-file: trigger.txt
  flyway:
    enabled: false
